# Generated by Django 2.2.7 on 2019-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191207_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
