# Generated by Django 2.2.7 on 2019-12-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='books/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
