# Generated by Django 2.2.7 on 2019-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191219_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
