# Generated by Django 2.2.7 on 2019-12-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191219_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m/%d', verbose_name='photo'),
        ),
    ]
