# Generated by Django 2.2.7 on 2019-12-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191219_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='imagin',
        ),
    ]
