# Generated by Django 2.2.7 on 2019-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191219_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='imagin',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
